### ISSUE TITLE
Bower support

### ISSUE THREAD

**Issue by vamsivarikuti** [apollographql/angular1-apollo#23]
AFAIK Most of angular1 projects are still using `bower`, Only some projects that has typescript with angular are using npm

Please add [bower support](https://bower.io/docs/creating-packages/), as it will be useful for more audience.

**Comment by stubailo** [comment]
I don't think that will be very helpful since all of the Apollo Client companion packages will be published only on `npm` as well, including the core `apollo-client` itself.

**Comment by vamsivarikuti** [comment]
@stubailo  Ok, Thanks for quick reply

So, the only way to use `angular1-apollo` is to migrate existing apps to `npm`?
OR 
Is there any plan for `bower`?

**Comment by stubailo** [comment]
You don't have to migrate anything right? You can use `npm` and `bower` in the same app.

**Comment by vamsivarikuti** [comment]
Yes, But all configs, tests, build tooling etc are tightly coupled to bower.
It's not easy to simply add `npm` in large projects

Bower can directly use github repo name to download the code, it would be useful to generate a build `.js` file to include in browser, in these repo's (apollo-client, angular1-apollo).

**Comment by stubailo** [comment]
I'll leave the question to @Urigo but personally I'd be against introducing official Bower support unless there is some way to automatically convert it from npm.

**Comment by Urigo** [comment]
@vamsivarikuti I actually understand that there is a lot of people on Angular 1 using bower.
But I agree with @stubailo that the best practice for long time has been to move to npm.

I don't mind though that the community will maintain a bower distribution of the library.
So what I suggest is that you will fork this library, add publish your fork to bower and keep it maintained and rebased with this repo.
Then you can PR the readme saying that there is a **community maintained** bower support and link to your repo. 
We won't take responsibility for it.
I hope that answers your needs

**Comment by vamsivarikuti** [comment]
I have tried creating bower package for `angular1-apollo`, it depends on `apollo-client`(npm), tried creating bower for that too, but it depends on lot of things that are not in bower. I am lost :) 

Now i understand the complexity in maintaining bower for this project

Actually i can't use graphql in my company, but i like it and want more people to use it.
Just thought if this is available in bower, more people can try this

**Comment by vamsivarikuti** [comment]
Bower is deprecated, their website recommends to use yarn/npm
