### ISSUE TITLE
Ability to use fragments

### ISSUE THREAD

**Issue by MattDionis** [apollographql/angular1-apollo#28]
I have not been able to find documentation regarding the use of fragments with angular1-apollo.
I currently set and reference common fields like below in order to "DRY" up my code, but I'm trying to determine if there is a way to use graphQL fragments instead.

```
const commonFields = `
  type
  name
  timestamp
  amount
`;

query: gql`
  query {
    scores {
      ${commonFields}
    }
  }
`
```

**Comment by kamilkisiela** [comment]
It should behave the same as in `apollo-angular` and `apollo-client`.

**Comment by kamilkisiela** [comment]
@MattDionis https://github.com/kamilkisiela/angular1-apollo-fragments

**Comment by kamilkisiela** [comment]
Docs: http://dev.apollodata.com/angular2/fragments.html

**Comment by MattDionis** [comment]
Excellent, thanks @kamilkisiela!
