### ISSUE TITLE
Does the package support apollo-client 2.0?

### ISSUE THREAD

**Issue by devonhumes** [apollographql/angular1-apollo#38]
With the recent release of apollo-client 2.0, the angular1-apollo library says that it doesn't support that version. Is this correct? Looking at the code, I don't see anything that would not work with the new client.

**Comment by kamilkisiela** [comment]
It will, thanks to #39

**Comment by jimthedev** [comment]
@devonhumes Can this be closed since 2.0 is supported?

**Comment by davidsandoz** [comment]
Is the support of apollo-client 2.0 released? I don't see on npm a new version of the library that is published after #39 has been merged.
