### ISSUE TITLE
 use with angularjs without import

### ISSUE THREAD

**Issue by GlauberF** [apollographql/angular1-apollo#46]
I would like to use the library with my application angularjs, but I can not use import to call the library because I do not use babel.

How could I use the library without using import, just inserting into my index

**Comment by kamilkisiela** [comment]
But why babel is required here? [We ship it](https://unpkg.com/angular1-apollo@0.3.0/build/src/index.js) as `commonjs` so `require('angular1-apollo'` is simply enough.

**Comment by florent1933** [comment]
@GlauberF , did you find a solution? I'm like you; I can't use Require. It's an old code with only grunt.

**Comment by florent1933** [comment]
@GlauberF , did you find a solution? I'm like you, I can't use Require. It's an old code with only grunt.

**Comment by GlauberF** [comment]
@florent1933  I migrated the application to angular latest versions

**Comment by florent1933** [comment]
Sad news for me. Thanks :)
